source 'https://rubygems.org'

gem 'sails'
gem 'activerecord'
gem 'sqlite3'
gem 'eventmachine'
gem 'thrift'

group :development, :test do
  # gem 'rspec'
  # gem 'factory_girl'
  # gem 'capistrano'
end